from enum import Enum


class State(Enum):
    DOLNOSLASKIE = 1
    KUJAWSKO_POMORSKIE = 2
    LUBELSKIE = 3
    LUBUSKIE = 4
    LODZKIE = 5
    MALOPOLSKIE = 6
    MAZOWIECKIE = 7
    OPOLSKIE = 8
    PODKARPACKIE = 9
    PODLASKIE = 10
    POMORSKIE = 11
    SLASKIE = 12
    SWIETOKRZYSKIE = 13
    WARMINSKO_MAZURSKIE = 14
    WIELKOPOLSKIE = 15
    ZACHODNIOPOMORSKIE = 16
